application: wikipythonwiki
version: 1
runtime: python27
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /ckeditor
  static_dir: ckeditor
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /.*
  script: main.py

